### ISSUE TITLE
exception in writePhasePed writePhase and in Pedigree.py

### ISSUE THREAD

**Issue by hindlem** [AlphaGenes/tinyhouse#1]
Pedigree.writePhasePed and Pedigree.writePhase expect ind.haplotypes to be n = 1|2 dimension np array (use ind.haplotypes.ndim) but this appears to be tuple. e.g see in line 155 of Pedigree it is set as a tuple of np int arrays.

An example command that causes this error...

AlphaImpute2 -out alphagenes/chr1_lowconfidence2/out -genotypes alphagenes/real_gens_alphagenes_chr1.genotype -pedigree real_gens_ped.txt -maxthreads 24 -phase_output -length .4630 -final_peeling_threshold 0.1

Stacktrace was...
```
Traceback (most recent call last):
  File "/home/mhindle/.local/bin/AlphaImpute2", line 8, in <module>
    sys.exit(main())
  File "/home/mhindle/.local/lib/python3.8/site-packages/alphaimpute2/tinyhouse/Utils.py", line 8, in timer
    values = func(*args, **kwargs)
  File "/home/mhindle/.local/lib/python3.8/site-packages/alphaimpute2/alphaimpute2.py", line 304, in main
    write_out_data(pedigree, args)
  File "/home/mhindle/.local/lib/python3.8/site-packages/alphaimpute2/tinyhouse/Utils.py", line 8, in timer
    values = func(*args, **kwargs)
  File "/home/mhindle/.local/lib/python3.8/site-packages/alphaimpute2/alphaimpute2.py", line 255, in write_out_data
    pedigree.writePhase(args.out + ".haplotypes")
  File "/home/mhindle/.local/lib/python3.8/site-packages/alphaimpute2/tinyhouse/Pedigree.py", line 943, in writePhase
    if ind.haplotypes.ndim == 2:  # diploid
AttributeError: 'tuple' object has no attribute 'ndim'
```

github AlphaImpute v0.0.3 and tinyhouse master checkout on 02/Jun/2021

**Comment by XingerTang** [comment]
This is fixed by #6. There are related discussions in #8, but as a fixed bug, this issue is completed.

**Comment by gregorgorjanc** [comment]
Thanks for linking PR and other discussion @XingerTang! This helps us track what has been done where etc.
